### ISSUE TITLE
token is exposed when requesting images

### ISSUE THREAD

**Issue by JonathanDoelan** [directus-community/nuxt-directus#102]
### Version

nuxt-directus 3.2.2
nuxt: 3.0.0

### Issue

When using `const { getThumbnail } = useDirectusFiles();` and getting the image via `getThumbnail(image, { ... })` and inserting it in a `<img :src="getThumbnail(image, { ... })">`, I have recognized, that the directus token is appended to the url inside the rendered `<img>` tag.

Isn’t that a security problem? I am using a token in order to prevent public access to my API.

**Comment by Intevel** [comment]
Hey, check out this comment: https://github.com/directus-community/nuxt-directus/issues/31#issuecomment-1128606254

Currently its not a bug, but a better support for static tokens is planned.

**Comment by JonathanDoelan** [comment]
@Intevel Thanks for the info. Is there any workaround? Is it possible to exclude the token for files? I am thinking of serving only the files via the public access/role without a token.
