### ISSUE TITLE
Cannot login when static token is revoked/deleted.

### ISSUE THREAD

**Issue by vagkalosynakis** [directus-community/nuxt-directus#111]
### Version

nuxt-directus: v3.2.2
nuxt: v3.2.0

### Reproduction Link

```
Not Applicable
```

### Steps to reproduce

1. Add a revoked static token to `nuxt.config.js`
2. Try to login using `useDirectusAuth()` using correct credentials

### What is Expected?

To be able to login.

### What is actually happening?

Getting `Invalid Credentials` error since the token is revoked but is forgotten inside the nuxt.config.js

### Final notes

We really should be able to have a boolean argument in the composables that decides if we want to use the nuxt config token or not.

At the moment it causes all kinds of bugs:

1. Firstly, the above bug. If someone removes or regenerates the static token from the Directus admin page, then not only does that user associated with the static token (Usually the website token) loses access to everything, but even legitimate users can't login.
2. I want to keep the granular permissions of each user in order for the to achieve the multi-tenancy inside the Admin page but I would like my application/website to be able to view/show all collections available to them. Currently, if I use the token to view a collection but then someone logs in successfully the static token, which was for the application is forgotten and I now lose access to everything. Currently If I need to have access to everything from the website but still allow users to use the Directus Auth, I have to do 2 entirely different implementations to disable the override of the static token or create a new set of Composables that ignore the use the static token based on a boolean value.

**Comment by Intevel** [comment]
@vagkalosynakis See https://github.com/directus-community/nuxt-directus/commit/6c17719f7dd316cd23d23b412b497671f34bf839
