### ISSUE TITLE
Release notes for 5.0.1

### ISSUE THREAD

**Issue by mklueh** [directus-community/nuxt-directus#112]
According to npm there has been a new release 5.0.1 and I wonder why and what has changed, as there is no pull request in the repository matching this release.

Also, why has the version 4 been skipped?

https://www.npmjs.com/package/nuxt-directus?activeTab=versions

**Comment by mklueh** [comment]
Ah I see, there is a changelog file within the package, so I'll close it :)

**Comment by Intevel** [comment]
@mklueh There was a Version 4.0, regarding to a breaking change the version was bumped to a new major version.

**Comment by casualmatt** [comment]
@Intevel, The documentation website needs to be updated?

**Comment by Intevel** [comment]
@casualmatt Im working on a completely new documentation.

**Comment by casualmatt** [comment]
Do you need any help, I'm not that grate of a dev but i can help in writing.

**Comment by Intevel** [comment]
Sure, send me a message on Discord!
