### ISSUE TITLE
Nuxt showing error page on failed login

### ISSUE THREAD

**Issue by matt-clegg** [directus-community/nuxt-directus#123]
### Version

nuxt-directus 5.1.1
nuxt: 3.3.2

### Steps to reproduce

Both my Nuxt frontend and Directus backend are running via docker-compose.

```vue
<script setup>

const {login} = useDirectusAuth();

const onSubmit = async () => {
    try{
        await login({
            email: "foo@example.com",
            password: "notapassword"
        })
    }catch(e){
        console.log("error", e.data);
    }
}
</script>
```
When the onSubmit method is called the login attempt it made. Directus returns a 401 as the user doesn't exist. Instead of the error being caught by the try catch, the page shows the nuxt error page:
![image](https://user-images.githubusercontent.com/34515355/229275477-b4bdcc85-994f-4846-8c48-140b4a6e8ae5.png)
![image](https://user-images.githubusercontent.com/34515355/229275482-83d034bb-c4ef-4f17-b2cf-2d372c7c1670.png)

### What is Expected?
The login error to be caught and handled in the try catch.

### What is actually happening?
The page is showing the nuxt error page.

**Comment by casualmatt** [comment]
We have implemented [Error handling](https://nuxt.com/docs/getting-started/error-handling#error-handling) by nuxt with  `showError`.

**Comment by casualmatt** [comment]
I found how to improve it even more by keeping support to catch. 

Working on fixing it.

**Comment by matt-clegg** [comment]
That would be great if it could be handled in the catch. 

As a work around I've found I can hide the Nuxt error page by calling `clearError()` in the catch statement. I'm not sure if this is best practice but it seems to work locally, I haven't tested this in prod.

```js
try {
  await login({
    email: 'foo@example.com',
    password: 'notapassword'
  })
} catch (e: any) {
  clearError()
}
```

**Comment by casualmatt** [comment]
Yes and no, 
it should work that you can use components and composables from nuxt to manage the error, one of those is clearError, but I will take a look if we can have the support for catch again. 

It was done to not leek directus URL directly on the error, but to just show the error itself, to support composables from nuxt to cancel the error or show it as you like.

**Comment by matt-clegg** [comment]
I've tried using the `<NuxtErrorBoundary>` component but it's still behaving the same way and showing the Nuxt error page.

pages/login.vue
```vue 
<template>
  <div>
    <h1>Login Page</h1>

    <NuxtErrorBoundary>
      <login-form />
      <template #error="{error}">
        <p>There was an error</p>
        <pre>{{ error }}</pre>
      </template>
    </NuxtErrorBoundary>
  </div>
</template>
```

components/LoginForm.vue
```vue
<template>
  <form @submit.prevent="onSubmit">
    <input v-model="email" type="email" placeholder="Email">
    <input v-model="password" type="password" placeholder="Password">
    <button type="submit">
      Login
    </button>
  </form>
</template>

<script setup lang="ts">

const email = ref('example@foo.com')
const password = ref('password123')

const { login } = useDirectusAuth()

const onSubmit = async () => {
  await login({
    email: email.value,
    password: password.value
  })
}

</script>
```

**Comment by casualmatt** [comment]
I'm working on it.

**Comment by casualmatt** [comment]
And the same is `createError`, which has different behavior server and client sides.

**Comment by casualmatt** [comment]
@matt-clegg 
Looking at nuxt documentation, and testing a bit, for now, the only way to manually manage error (SSR + CSR) is to use nuxt composables and components. 
That means, as advised on the nuxt documentation using `clearError()` and, if you want, using it to redirect the end user. 

Using nuxt [Error handling](https://nuxt.com/docs/getting-started/error-handling#error-handling) allows us to support custom error pages and nuxt specific features; that using catch would not be available and need to be coded by the developer. 

I will improve the module so that it will throw errors and that catch can be used more effectively. 

@Intevel 
Should I change to [createError](https://nuxt.com/docs/getting-started/error-handling#createerror) or keep [showError](https://nuxt.com/docs/getting-started/error-handling#showerror) to maintain consistency in both SSR and CSR?

**Comment by Intevel** [comment]
> @matt-clegg 
> 
> Looking at nuxt documentation, and testing a bit, for now, the only way to manually manage error (SSR + CSR) is to use nuxt composables and components. 
> 
> That means, as advised on the nuxt documentation using `clearError()` and, if you want, using it to redirect the end user. 
> 
> 
> 
> Using nuxt [Error handling](https://nuxt.com/docs/getting-started/error-handling#error-handling) allows us to support custom error pages and nuxt specific features; that using catch would not be available and need to be coded by the developer. 
> 
> 
> 
> I will improve the module so that it will throw errors and that catch can be used more effectively. 
> 
> 
> 
> @Intevel 
> 
> Should I change to [createError](https://nuxt.com/docs/getting-started/error-handling#createerror) or keep [showError](https://nuxt.com/docs/getting-started/error-handling#showerror) to maintain consistency in both SSR and CSR? 

We should use createError

**Comment by casualmatt** [comment]
I will change to that this weekend

**Comment by casualmatt** [comment]
#124 
Here it is. 
Better support for try-catch even if you need to use `clearError()` to manage the error manually. 

In dev mode, it will give back the complete error; in production, it will give back just code and message to not leak any information.
