### ISSUE TITLE
Refresh token cookie not clearing after logging out

### ISSUE THREAD

**Issue by matt-clegg** [directus-community/nuxt-directus#129]
I've been trying to setup some automatic token refresh using middleware. If I log the user out and then open the page in a new tab, the middleware will call `refreshTokens()` and fail with `401 Unauthorized`.

I'm not sure if this is indended behaviour or not, but the `directus_refresh_token` cookie persists after the user logs out. 

Should I be adding some additional checks to see if the `directus_token` cookie exists before calling `refreshTokens()`, or does the `directus_refresh_token` need to be cleared after logging out?

### Version

nuxt-directus: v5.1.2
nuxt: v3.3.2

### Steps to reproduce

1. Login to directus with the `login()` method from the `useDirectusAuth` composable.
2. Call the `logout()` method from the `useDirectusAuth` composable.
3. Inspect the `directus_refresh_token` cookie using `const refreshToken = useCookie("directus_refresh_token");`.

### What is Expected?

The `directus_refresh_token` should be cleared after calling logout from the `useDirectusAuth` composable. 

### What is actually happening?

The `directus_refresh_token` still persists after calling logout.

**Comment by Intevel** [comment]
This is definitely a bug. Thanks for reporting. I will fix this

**Comment by Intevel** [comment]
Fixed with 5.1.3
