### ISSUE TITLE
How to pull images dynamically?

### ISSUE THREAD

**Issue by bastianhilton** [directus-community/nuxt-directus#132]
Hello i see how to pull images with the fileId here: https://nuxt-directus.netlify.app/usage/useDirectusFiles

But on a dynamic page how to pull the images without having to specify the individual file name

This is what I have so far:

```
<v-carousel><v-carousel-item :src="departments.media" cover></v-carousel-item></v-carousel>

<script setup>
    useHead({
        title: 'Department',
    })

    const {
        getItemById
    } = useDirectusItems();
    const route = useRoute();

    const departments = await getItemById({
        collection: "departments",
        id: route.params.id
    });
    if (!departments) throwError("No Department found, 404");

    const {
        getThumbnail: img
    } = useDirectusFiles();
</script>
```

This way isn't working, i'm pulling all other content but not the media which is using the files content type

**Comment by casualmatt** [comment]
You need to use the composable function to convert a UUID of an image to a URL.
```vue    
<img :src="img(fileId)"/>  
 
```

**Comment by bastianhilton** [comment]
right but how do I specify the fileId dynamically or do I have to put a fileId to get it to work?

**Comment by bastianhilton** [comment]
nevermind I found the solution, basically I switched to the image input type and updated my code to 

<v-carousel>
            <v-carousel-item :src="`http://example.com:8011/assets/${departments.image}`" cover></v-carousel-item>
        </v-carousel>

Also I gave read permissions to Directus_files and Directus_folders from the roles & permissions section in the Directus Admin.
