### ISSUE TITLE
Auth tokens not refreshed.

### ISSUE THREAD

**Issue by gecode-es** [directus-community/nuxt-directus#56]
nuxt-directus 
nuxt: 

### Steps to reproduce

Use nuxt-directus to login and issue API requests. These requests will start to fail when the Auth token_expires.

Directus default token expiry is 15 minutes with a refresh_token validity of 7 days. nuxt-directus does not appear to have any support for handling expired tokens.

There is a PR https://github.com/Intevel/nuxt-directus/pull/45 which does not appear to work either.

**Comment by Intevel** [comment]
@gecode-es This feature isnt implemented yet. I am working on it, take a look at #15

**Comment by paulvonber** [comment]
Any updates on this?

**Comment by Intevel** [comment]
With the last release I added the functions to manually refresh the tokens. That the token is refreshed automatically is still missing 🎉 .

**Comment by casualmatt** [comment]
I just added the documentation; it will be available as soon as the new v5 docs is public

**Comment by tillsanders** [comment]
> I just added the documentation; it will be available as soon as the new v5 docs is public

Hi, if I understand correctly, this feature is available now? The documentation seems to be outdated though. Or am I missing something? How do I use it?

<img width="716" alt="Bildschirmfoto 2023-09-07 um 01 26 34" src="https://github.com/Intevel/nuxt-directus/assets/1533846/cad5d23d-3964-4ee9-9fdc-4820a961eb85">

Simple and manual are almost identical.

**Comment by BorisKamp** [comment]
Bump, whats up with this?

**Comment by Sandros94** [comment]
> Bump, whats up with this?

One of the reasons that this became stale is because of #215

But also that development is facing some roadblocks delaying everything even further

**Comment by vwasteels** [comment]
Hello,

Is there any news on this ?
Do you have any recommandation on how to implement manual refresh ? is it before any request ?

Thanks

**Comment by Neeptossss** [comment]
> Hello,
> 
> Is there any news on this ? Do you have any recommandation on how to implement manual refresh ? is it before any request ?
> 
> Thanks

If you want to achieve request based token refresh, you can find in the module configuration type the autoRefresh option which should check for expired token to refresh before every request and then prevent 401s https://github.com/Intevel/nuxt-directus/blob/f7c6cfa67d6de11fbf0aa849b1a973825049a21d/src/runtime/composables/useDirectus.ts#L20 However tokens can simply be refreshed using the refreshTokens() methods through a middleware for navigation based refresh (not request ^^).

nitpick: In the module type declaration the TSDoc mention that the default value for autoRefresh is true https://github.com/Intevel/nuxt-directus/blob/f7c6cfa67d6de11fbf0aa849b1a973825049a21d/src/module.ts#L25 but in the documentation it mention false https://github.com/Intevel/nuxt-directus/blob/f7c6cfa67d6de11fbf0aa849b1a973825049a21d/docs/content/1.getting-started/2.options.md?plain=1#L30
cc @casualmatt 

Thanks :)
