### ISSUE TITLE
[request error] [unhandled] [500] nuxt instance unavailable in pinia store

### ISSUE THREAD

**Issue by dataexcess** [directus-community/nuxt-directus#88]
### Version

nuxt-directus 3.2.2
nuxt: 3.0.0-rc.13

### Steps to reproduce

use the useDirectus methods inside a pinia store...

### What is Expected?

for it to work

### What is actually happening?

pinia apparently does not have access to the nuxt instance. This is unfortunate as I would mainly like to use useDirectus inside my pinia store. Not sure if this is something you can fix, but wantesd to make really sure that this is not possible or if I'm doing something wrong.

**Comment by rijkvanzanten** [comment]
While I'm not a Nuxt user myself, it definitely sounds like a Nuxt scoping issue to me 🤔

**Comment by dataexcess** [comment]
I guess so :( 
It's just unfortunate because then I have to call myStore.myDataArray = useDirectus.getCollection('myData') inside a component while ideally I would prefer to have this logic contained in the store itself.
But it's not the end of the world... lol

**Comment by rijkvanzanten** [comment]
How / where are you calling the pinia method that's doing that call? As long as that method is called within the context of a Vue component it might still work?

**Comment by dataexcess** [comment]
Nope. I am calling it in a component. 
It seems it doesn't matter. Inside the pinia store the scope does not have access to nuxt.

**Comment by dataexcess** [comment]
Same problem when I abstract that code away in a composable by the way :D 
No way to escape it, I have to use the useDirectus methods directly inside a vue component to make it work.

**Comment by smokeyfro** [comment]
@dataexcess not sure of your implementation approach, but this is how I'm using the Directus composables in my Pinia store -> https://gist.github.com/smokeyfro/791fdec3a6a6065f559d63927512799f. Hopefully that helps :)

**Comment by Intevel** [comment]
@dataexcess Do you still have this bug?
